name: diafall
version: 1.0.0
main: io.github.found_cake.diafall.Loader
description: SecurityFirst 연말 CTF
author: found_cake
api-version: '1.21.10'

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.2.20
  - org.jetbrains.kotlin:kotlin-reflect:2.2.20
  - org.jetbrains.exposed:exposed-core:0.61.0
  - org.jetbrains.exposed:exposed-dao:0.61.0
  - org.jetbrains.exposed:exposed-jdbc:0.61.0
  - org.xerial:sqlite-jdbc:3.51.0.0